server:
    port: 1002

spring:
    main:
        web-application-type: servlet

    profiles:
        default: local
    
    application:
        name: payment-service
    
    config:
        import:
            - security/application-db.yml
            - security/application-oauth2.yml
            - security/application-iamport.yml
