spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${local-db.postgres.host}:${local-db.postgres.port}/${local-db.postgres.name}
      username: ${local-db.postgres.username}
      password: ${local-db.postgres.password}

  jpa:
    properties:
      hibernate:
        format:
            sql: true
        highlight:
            sql: true
        hbm2ddl:
            auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true

iamport:
  api-secret: ${local-iamport.api-secret}
  base-url: https://api.portone.io
  mid-key: ${local-iamport.mid-key}
  webhook-secret: ${local-iamport.webhook-secret}
  channel-key: ${local-iamport.channel-key}

logging:
  level:
    org:
      hibernate:
        type: info
        level: info
